using System.Collections;

namespace MegaSkin.Checker
{
    class IDS
    {
        public static Hashtable Skins = new Hashtable
        {
            { "cid_009_athena_commando_m", "Tracker" },
            { "cid_010_athena_commando_m", "Ranger" },
            { "cid_011_athena_commando_m", "Scout" },
            { "cid_012_athena_commando_m", "Trooper" },
            { "cid_013_athena_commando_f", "Renegade" },
            { "cid_014_athena_commando_f", "Pathfinder" },
            { "cid_015_athena_commando_f", "Assault Trooper" },
            { "cid_016_athena_commando_f", "Commando" },
            { "cid_017_athena_commando_m", "Aerial Assault Trooper" },
            { "cid_018_athena_commando_m", "Recon Scout" },
            { "cid_019_athena_commando_m", "Infiltrator" },
            { "cid_020_athena_commando_m", "Special Forces" },
            { "cid_021_athena_commando_f", "Brawler" },
            { "cid_022_athena_commando_f", "Recon Expert" },
            { "cid_023_athena_commando_f", "Munitions Expert" },
            { "cid_024_athena_commando_f", "Recon Specialist" },
            { "cid_025_athena_commando_m", "First strike Specialist" },
            { "cid_026_athena_commando_m", "Desperado" },
            { "cid_027_athena_commando_f", "Survival Specialist" },
            { "cid_028_athena_commando_f", "Renegade Raider" },
            { "cid_029_athena_commando_f_halloween", "Ghoul Trooper" },
            { "cid_030_athena_commando_m_halloween", "Skull Trooper" },
            { "cid_031_athena_commando_m_retro", "Raptor" },
            { "cid_032_athena_commando_m_medieval", "Blue Squire" },
            { "cid_033_athena_commando_f_medieval", "Royale Knight" },
            { "cid_034_athena_commando_f_medieval", "Red Knight" },
            { "cid_035_athena_commando_m_medieval", "Black Knight" },
            { "cid_036_athena_commando_m_wintercamo", "Absolute Zero" },
            { "cid_037_athena_commando_f_wintercamo", "Arctic Assassin" },
            { "cid_038_athena_commando_m_disco", "Funk Ops" },
            { "cid_039_athena_commando_f_disco", "Sparkle Specialist" },
            { "cid_040_athena_commando_m_district", "Devastator" },
            { "cid_041_athena_commando_f_district", "Dominator" },
            { "cid_042_athena_commando_m_cyberpunk", "Circuit Breaker" },
            { "cid_043_athena_commando_f_stealth", "Shadow Ops" },
            { "cid_044_athena_commando_f_scipop", "Brite Bomber" },
            { "cid_045_athena_commando_m_holidaysweater", "Yuletide Ranger" },
            { "cid_046_athena_commando_f_holidaysweater", "Nog Ops" },
            { "cid_047_athena_commando_f_holidayreindeer", "Red-Nosed Raider" },
            { "cid_048_athena_commando_f_holidaygingerbread", "Ginger Gunner" },
            { "cid_049_athena_commando_m_holidaygingerbread", "Merry Marauder" },
            { "cid_050_athena_commando_m_holidaynutcracker", "Crackshot" },
            { "cid_051_athena_commando_m_holidayelf", "Codename E.L.F." },
            { "cid_052_athena_commando_f_psblue", "Blue Team Leader" },
            { "cid_053_athena_commando_m_skidude", "Alpine Ace" },
            { "cid_054_athena_commando_m_skidude_usa", "Alpine Ace (USA)" },
            { "cid_055_athena_commando_m_skidude_can", "Alpine Ace (CAN)" },
            { "cid_056_athena_commando_m_skidude_gbr", "Alpine Ace (GBR)" },
            { "cid_057_athena_commando_m_skidude_fra", "Alpine Ace (FRA)" },
            { "cid_058_athena_commando_m_skidude_ger", "Alpine Ace (GER)" },
            { "cid_059_athena_commando_m_skidude_chn", "Alpine Ace (CHN)" },
            { "cid_060_athena_commando_m_skidude_kor", "Alpine Ace (KOR)" },
            { "cid_061_athena_commando_f_skigirl", "Mogul Master" },
            { "cid_062_athena_commando_f_skigirl_usa", "Mogul Master (USA)" },
            { "cid_063_athena_commando_f_skigirl_can", "Mogul Master (CAN)" },
            { "cid_064_athena_commando_f_skigirl_gbr", "Mogul Master (GBR)" },
            { "cid_065_athena_commando_f_skigirl_fra", "Mogul Master (FRA)" },
            { "cid_066_athena_commando_f_skigirl_ger", "Mogul Master (GER)" },
            { "cid_067_athena_commando_f_skigirl_chn", "Mogul Master (CHN)" },
            { "cid_068_athena_commando_f_skigirl_kor", "Mogul Master (KOR)" },
            { "cid_069_athena_commando_f_pinkbear", "Cuddle Team Leader" },
            { "cid_070_athena_commando_m_cupid", "Love Ranger" },
            { "cid_071_athena_commando_m_wukong", "Wukong" },
            { "cid_072_athena_commando_m_scout", "Sash Sergeant" },
            { "cid_073_athena_commando_f_scuba", "Snorkel Ops" },
            { "cid_074_athena_commando_f_stripe", "Jungle Scout" },
            { "cid_075_athena_commando_f_stripe", "Tactics Officer" },
            { "cid_076_athena_commando_f_sup", "Dazzle" },
            { "cid_077_athena_commando_m_sup", "Hyperion" },
            { "cid_078_athena_commando_m_camo", "Highrise Assault Trooper" },
            { "cid_079_athena_commando_f_camo", "Tower Recon Specialist" },
            { "cid_080_athena_commando_m_space", "Mission Specialist" },
            { "cid_081_athena_commando_f_space", "Moonwalker" },
            { "cid_082_athena_commando_m_scavenger", "Rust Lord" },
            { "cid_083_athena_commando_f_tactical", "Elite Agent" },
            { "cid_084_athena_commando_m_assassin", "The Reaper" },
            { "cid_085_athena_commando_m_twitch", "Sub Commander" },
            { "cid_086_athena_commando_m_redsilk", "Crimson Scout" },
            { "cid_087_athena_commando_f_redsilk", "Scarlet Defender" },
            { "cid_088_athena_commando_m_spaceblack", "Dark Voyager" },
            { "cid_089_athena_commando_m_retrogrey", "Havoc" },
            { "cid_090_athena_commando_m_tactical", "Rogue Agent" },
            { "cid_091_athena_commando_m_redshirt", "Radiant Striker" },
            { "cid_092_athena_commando_f_redshirt", "Brilliant Striker" },
            { "cid_093_athena_commando_m_dinosaur", "Rex" },
            { "cid_094_athena_commando_m_rider", "Burnout" },
            { "cid_095_athena_commando_m_founder", "Warpaint" },
            { "cid_096_athena_commando_f_founder", "Rose Team Leader" },
            { "cid_097_athena_commando_f_rockerpunk", "Power Chord" },
            { "cid_098_athena_commando_f_stpatty", "Sgt. Green Clover" },
            { "cid_099_athena_commando_f_scathach", "Highland Warrior" },
            { "cid_100_athena_commando_m_cuchulainn", "Battle Hound" },
            { "cid_101_athena_commando_m_stealth", "Midnight Ops" },
            { "cid_102_athena_commando_m_raven", "Raven" },
            { "cid_103_athena_commando_m_bunny", "Rabbit Raider" },
            { "cid_104_athena_commando_f_bunny", "Bunny Brawler" },
            { "cid_105_athena_commando_f_spaceblack", "Dark Vanguard" },
            { "cid_106_athena_commando_f_taxi", "Whiplash" },
            { "cid_107_athena_commando_f_pajamaparty", "Tricera Ops" },
            { "cid_108_athena_commando_m_fishhead", "Leviathan" },
            { "cid_109_athena_commando_m_pizza", "Tomatohead" },
            { "cid_110_athena_commando_f_circuitbreaker", "Cipher" },
            { "cid_111_athena_commando_f_robo", "Steelsight" },
            { "cid_112_athena_commando_m_brite", "Brite Gunner" },
            { "cid_113_athena_commando_m_blueace", "Royale Bomber" },
            { "cid_114_athena_commando_f_tacticalwoodland", "Trailblazer" },
            { "cid_115_athena_commando_m_carbideblue", "Carbide" },
            { "cid_116_athena_commando_m_carbideblack", "Omega" },
            { "cid_117_athena_commando_m_tacticaljungle", "Squad Leader" },
            { "cid_118_athena_commando_f_valor", "Valor" },
            { "cid_119_athena_commando_f_candy", "Zoey" },
            { "cid_120_athena_commando_f_graffiti", "Teknique" },
            { "cid_121_athena_commando_m_graffiti", "Abstrakt" },
            { "cid_122_athena_commando_m_metal", "Diecast" },
            { "cid_123_athena_commando_f_metal", "Chromium" },
            { "cid_124_athena_commando_f_auroraglow", "Nitelite" },
            { "cid_125_athena_commando_m_tacticalwoodland", "Battlehawk" },
            { "cid_126_athena_commando_m_auroraglow", "Liteshow" },
            { "cid_127_athena_commando_m_hazmat", "Toxic Trooper" },
            { "cid_128_athena_commando_f_hazmat", "Hazard Agent" },
            { "cid_129_athena_commando_m_deco_retouch", "Venturion" },
            { "cid_130_athena_commando_m_merman", "Moisty Merman" },
            { "cid_131_athena_commando_m_warpaint", "Bandolier" },
            { "cid_132_athena_commando_m_venus", "Flytrap" },
            { "cid_133_athena_commando_f_deco", "Ventura" },
            { "cid_134_athena_commando_m_jailbird", "Scoundrel" },
            { "cid_135_athena_commando_f_jailbird", "Rapscallion" },
            { "cid_136_athena_commando_m_basketball", "Jumpshot" },
            { "cid_137_athena_commando_f_basketball", "Triple Threat" },
            { "cid_138_athena_commando_m_psburnout", "Blue Striker" },
            { "cid_139_athena_commando_m_fighterpilot", "Wingman" },
            { "cid_140_athena_commando_m_visitor", "The Visitor" },
            { "cid_141_athena_commando_m_darkeagle", "Omen" },
            { "cid_142_athena_commando_m_wwiipilot", "Sky Stalker" },
            { "cid_143_athena_commando_f_darkninja", "Fate" },
            { "cid_144_athena_commando_m_soccerdudea", "Super Striker" },
            { "cid_145_athena_commando_m_soccerdudeb", "Midfield Maestro" },
            { "cid_146_athena_commando_m_soccerdudec", "Aerial Threat" },
            { "cid_147_athena_commando_m_soccerduded", "Stalwart Sweeper" },
            { "cid_148_athena_commando_f_soccergirla", "Dynamic Dribbler" },
            { "cid_149_athena_commando_f_soccergirlb", "Poised Playmaker" },
            { "cid_150_athena_commando_f_soccergirlc", "Clinical Crosser" },
            { "cid_151_athena_commando_f_soccergirld", "Finesse Finisher" },
            { "cid_152_athena_commando_f_carbideorange", "Criterion" },
            { "cid_153_athena_commando_f_carbideblack", "Oblivion" },
            { "cid_154_athena_commando_m_gumshoe", "Sleuth" },
            { "cid_155_athena_commando_f_gumshoe", "Gumshoe" },
            { "cid_156_athena_commando_f_fuzzybearind", "Fireworks Team Leader" },
            { "cid_157_athena_commando_m_starsandstripes", "Star-Spangled Trooper" },
            { "cid_158_athena_commando_f_starsandstripes", "Star-Spangled Ranger" },
            { "cid_159_athena_commando_m_gumshoedark", "Noir" },
            { "cid_160_athena_commando_m_speedyred", "Vertex" },
            { "cid_161_athena_commando_m_drift", "Drift" },
            { "cid_162_athena_commando_f_streetracer", "Redline" },
            { "cid_163_athena_commando_f_viking", "Huntress" },
            { "cid_164_athena_commando_m_viking", "Magnus" },
            { "cid_165_athena_commando_m_darkviking", "Ragnarok" },
            { "cid_166_athena_commando_f_lifeguard", "Sun Strider" },
            { "cid_167_athena_commando_m_tacticalbadass", "Sledgehammer" },
            { "cid_168_athena_commando_m_shark", "Chomp Sr." },
            { "cid_169_athena_commando_m_luchador", "Masked Fury" },
            { "cid_170_athena_commando_f_luchador", "Dynamo" },
            { "cid_171_athena_commando_m_sharpdresser", "Moniker" },
            { "cid_172_athena_commando_f_sharpdresser", "Fortune" },
            { "cid_173_athena_commando_f_starfishuniform", "Rook" },
            { "cid_174_athena_commando_f_carbidewhite", "Eon" },
            { "cid_175_athena_commando_m_celestial", "Galaxy" },
            { "cid_176_athena_commando_m_lifeguard", "Sun Tan Specialist" },
            { "cid_177_athena_commando_m_streetracercobra", "Maverick" },
            { "cid_178_athena_commando_f_streetracercobra", "Shade" },
            { "cid_179_athena_commando_f_scuba", "Reef Ranger" },
            { "cid_180_athena_commando_m_scuba", "Wreck Raider" },
            { "cid_182_athena_commando_m_modernmilitary", "Archetype" },
            { "cid_183_athena_commando_m_modernmilitaryred", "Double Helix" },
            { "cid_185_athena_commando_m_durrburgerhero", "Beef Boss" },
            { "cid_186_athena_commando_m_exercise", "Mullet Marauder" },
            { "cid_187_athena_commando_f_fuzzybearpanda", "P.A.N.D.A Team Leader" },
            { "cid_188_athena_commando_f_streetracerwhite", "Whiteout" },
            { "cid_189_athena_commando_f_exercise", "Aerobic Assassin" },
            { "cid_190_athena_commando_m_streetracerwhite", "Overtaker" },
            { "cid_191_athena_commando_m_sushichef", "Sushi Master" },
            { "cid_192_athena_commando_m_hippie", "Far Out Man" },
            { "cid_193_athena_commando_f_hippie", "Dreamflower" },
            { "cid_194_athena_commando_f_ravenquill", "Ravage" },
            { "cid_195_athena_commando_f_bling", "The Ace" },
            { "cid_196_athena_commando_m_biker", "Backbone" },
            { "cid_197_athena_commando_f_biker", "Chopper" },
            { "cid_198_athena_commando_m_bluesamurai", "Musha" },
            { "cid_199_athena_commando_f_bluesamurai", "Hime" },
            { "cid_200_athena_commando_m_darkpaintballer", "Enforcer" },
            { "cid_201_athena_commando_m_desertops", "Armadillo" },
            { "cid_202_athena_commando_f_desertops", "Scorpion" },
            { "cid_203_athena_commando_m_cloakedstar", "Cloaked Star" },
            { "cid_204_athena_commando_m_garageband", "Stage Slayer" },
            { "cid_205_athena_commando_f_garageband", "Synth Star" },
            { "cid_206_athena_commando_m_bling", "Wild Card" },
            { "cid_207_athena_commando_m_footballdudea", "End Zone" },
            { "cid_208_athena_commando_m_footballdudeb", "Gridiron" },
            { "cid_209_athena_commando_m_footballdudec", "Spike" },
            { "cid_210_athena_commando_f_footballgirla", "Blitz" },
            { "cid_211_athena_commando_f_footballgirlb", "Rush" },
            { "cid_212_athena_commando_f_footballgirlc", "Interceptor" },
            { "cid_214_athena_commando_f_footballreferee", "Whistle Warrior" },
            { "cid_215_athena_commando_m_footballreferee", "Striped Soldier" },
            { "cid_216_athena_commando_f_medic", "Field Surgeon" },
            { "cid_217_athena_commando_m_medic", "Triage Trooper" },
            { "cid_218_athena_commando_m_greenberet", "Garrison" },
            { "cid_219_athena_commando_m_hacivat", "Hacivat" },
            { "cid_220_athena_commando_f_clown", "Peekaboo" },
            { "cid_221_athena_commando_m_clown", "Nite Nite" },
            { "cid_222_athena_commando_f_darkviking", "Valkyrie" },
            { "cid_223_athena_commando_m_dieselpunk", "Maximillian" },
            { "cid_224_athena_commando_f_dieselpunk", "Airheart" },
            { "cid_225_athena_commando_m_octoberfest", "Ludwig" },
            { "cid_226_athena_commando_f_octoberfest", "Heidi" },
            { "cid_227_athena_commando_f_vampire", "Dusk" },
            { "cid_228_athena_commando_m_vampire", "Sanctum" },
            { "cid_229_athena_commando_f_darkbomber", "Dark Bomber" },
            { "cid_230_athena_commando_m_werewolf", "Dire" },
            { "cid_231_athena_commando_f_redriding", "Fable" },
            { "cid_232_athena_commando_f_halloweentomato", "Nightshade" },
            { "cid_233_athena_commando_m_fortnitedj", "DJ Yonder" },
            { "cid_234_athena_commando_m_llamarider", "Giddy-up" },
            { "cid_235_athena_commando_m_scarecrow", "Hay Man" },
            { "cid_236_athena_commando_f_scarecrow", "Straw Ops" },
            { "cid_237_athena_commando_f_cowgirl", "Calamity" },
            { "cid_238_athena_commando_f_footballgirld", "Juke" },
            { "cid_239_athena_commando_m_footballduded", "Strong Guard" },
            { "cid_240_athena_commando_f_plague", "Scourge" },
            { "cid_241_athena_commando_m_plague", "Plague" },
            { "cid_242_athena_commando_f_bullseye", "Bullseye" },
            { "cid_243_athena_commando_m_pumpkinslice", "Hallowhead" },
            { "cid_244_athena_commando_m_pumpkinsuit", "Jack Gourdon" },
            { "cid_245_athena_commando_f_durrburgerpjs", "Onesie" },
            { "cid_246_athena_commando_f_grave", "Skull Ranger" },
            { "cid_247_athena_commando_m_guanyu", "Guan Yu" },
            { "cid_248_athena_commando_m_blackwidow", "Spider Knight" },
            { "cid_249_athena_commando_f_blackwidow", "Arachne" },
            { "cid_250_athena_commando_m_evilcowboy", "Deadfire" },
            { "cid_251_athena_commando_f_muertos", "Rosa" },
            { "cid_252_athena_commando_m_muertos", "Dante" },
            { "cid_253_athena_commando_m_militaryfashion2", "Summit Striker" },
            { "cid_254_athena_commando_m_zombie", "Brainiac" },
            { "cid_256_athena_commando_m_pumpkin", "Patch Patroller" },
            { "cid_257_athena_commando_m_samuraiultra", "Shogun" },
            { "cid_258_athena_commando_f_fuzzybearhalloween", "Spooky Team Leader" },
            { "cid_259_athena_commando_m_streetops", "Reflex" },
            { "cid_260_athena_commando_f_streetops", "Instinct" },
            { "cid_261_athena_commando_m_raptorarcticcamo", "Frostbite" },
            { "cid_262_athena_commando_m_madcommander", "Ruckus" },
            { "cid_263_athena_commando_f_madcommander", "Mayhem" },
            { "cid_264_athena_commando_m_animaljackets", "Growler" },
            { "cid_265_athena_commando_f_animaljackets", "Flapjackie" },
            { "cid_266_athena_commando_f_llamarider", "Yee-Haw!" },
            { "cid_267_athena_commando_m_robotred", "A.I.M" },
            { "cid_268_athena_commando_m_rockerpunk", "Riot" },
            { "cid_269_athena_commando_m_wizard", "Castor" },
            { "cid_270_athena_commando_f_witch", "Elmira" },
            { "cid_271_athena_commando_f_sushichef", "Maki Master" },
            { "cid_272_athena_commando_m_hornedmask", "Taro" },
            { "cid_273_athena_commando_f_hornedmask", "Nara" },
            { "cid_274_athena_commando_m_feathers", "Tender Defender" },
            { "cid_275_athena_commando_m_sniperhood", "Longshot" },
            { "cid_276_athena_commando_f_sniperhood", "Insight" },
            { "cid_277_athena_commando_m_moth", "Mothmando" },
            { "cid_278_athena_commando_m_yeti", "Trog" },
            { "cid_279_athena_commando_m_tacticalsanta", "Sgt. Winter" },
            { "cid_280_athena_commando_m_snowman", "Slushy Soldier" },
            { "cid_281_athena_commando_f_snowboard", "Powder" },
            { "cid_286_athena_commando_f_neoncat", "Lynx" },
            { "cid_287_athena_commando_m_arcticsniper", "Zenith" },
            { "cid_288_athena_commando_m_iceking", "The Ice King" },
            { "cid_290_athena_commando_f_bluebadass", "Waypoint" },
            { "cid_291_athena_commando_m_dieselpunk02", "Cloudbreaker" },
            { "cid_292_athena_commando_f_dieselpunk02", "Wingtip" },
            { "cid_293_athena_commando_m_ravenwinter", "Frozen Raven" },
            { "cid_294_athena_commando_f_redknightwinter", "Frozen Red Knight" },
            { "cid_295_athena_commando_m_cupidwinter", "Frozen Love Ranger" },
            { "cid_296_athena_commando_m_math", "Prodigy" },
            { "cid_297_athena_commando_f_math", "Maven" },
            { "cid_298_athena_commando_f_icemaiden", "Glimmer" },
            { "cid_299_athena_commando_m_snowninja", "Snowfoot" },
            { "cid_300_athena_commando_f_angel", "Ark" },
            { "cid_302_athena_commando_f_nutcracker", "Crackabella" },
            { "cid_303_athena_commando_f_snowfairy", "Sugarplum" },
            { "cid_304_athena_commando_m_gnome", "Grimbles" },
            { "cid_308_athena_commando_f_fortnitedj", "DJ Bop" },
            { "cid_309_athena_commando_m_streetgoth", "Paradox" },
            { "cid_310_athena_commando_f_streetgoth", "Lace" },
            { "cid_311_athena_commando_m_reindeer", "Red-nosed Ranger" },
            { "cid_312_athena_commando_f_funkops", "Disco Diva" },
            { "cid_314_athena_commando_m_krampus", "Krampus" },
            { "cid_315_athena_commando_m_teriyakifish", "Fishstick" },
            { "cid_316_athena_commando_f_winterholiday", "Tinseltoes" },
            { "cid_317_athena_commando_m_winterghoul", "Cloaked Shadow" },
            { "cid_318_athena_commando_m_demon", "Malcore" },
            { "cid_321_athena_commando_m_militaryfashion1", "Verge" },
            { "cid_322_athena_commando_m_techops", "Tech Ops" },
            { "cid_323_athena_commando_m_barbarian", "Jaeger" },
            { "cid_324_athena_commando_f_barbarian", "Fyra" },
            { "cid_327_athena_commando_m_bluemystery", "Cobalt" },
            { "cid_331_athena_commando_m_taxi", "Cabbie" },
            { "cid_336_athena_commando_m_dragonmask", "Firewalker" },
            { "cid_339_athena_commando_m_robottrouble", "Revolt" },
            { "cid_340_athena_commando_f_robottrouble", "Rebel" },
            { "cid_341_athena_commando_f_skullbrite", "Skully" },
            { "cid_342_athena_commando_m_streetracermetallic", "Honor Guard" },
            { "cid_343_athena_commando_m_cupiddark", "Fallen Love Ranger" },
            { "cid_344_athena_commando_m_icecream", "Lil Whip" },
            { "cid_313_athena_commando_m_kpopfashion", "IKONIK" },
            { "cid_325_athena_commando_m_wavyman", "Bendie" },
            { "cid_326_athena_commando_f_wavyman", "Twistie" },
            { "cid_346_athena_commando_m_dragonninja", "Hybrid" },
            { "cid_347_athena_commando_m_pirateprogressive", "Blackheart" },
            { "cid_348_athena_commando_f_medusa", "Sidewinder" },
            { "cid_349_athena_commando_m_banana", "Peely" },
            { "cid_350_athena_commando_m_masterkey", "Master Key" },
            { "cid_351_athena_commando_f_fireelf", "Ember" },
            { "cid_352_athena_commando_f_shiny", "Luxe" },
            { "cid_353_athena_commando_f_bandolier", "Bandolette" },
            { "cid_354_athena_commando_m_munitionsexpert", "Munitions Major" },
            { "cid_355_athena_commando_m_farmer", "Hayseed" },
            { "cid_356_athena_commando_f_farmer", "Sunflower" },
            { "cid_357_athena_commando_m_orangecamo", "Hypernova" },
            { "cid_358_athena_commando_m_aztec", "Mezmer" },
            { "cid_359_athena_commando_f_aztec", "Sunbird" },
            { "cid_360_athena_commando_m_techopsblue", "Carbon Commando" },
            { "cid_361_athena_commando_m_bandageninja", "Kenji" },
            { "cid_362_athena_commando_f_bandageninja", "Kuno" },
            { "cid_363_athena_commando_m_sciops", "Axiom" },
            { "cid_364_athena_commando_f_sciops", "Psion" },
            { "cid_366_athena_commando_m_tropical", "Marino" },
            { "cid_367_athena_commando_f_tropical", "Laguna" },
            { "cid_369_athena_commando_f_devilrock", "Malice" },
            { "cid_370_athena_commando_m_evilsuit", "Inferno" },
            { "cid_372_athena_commando_f_pirate01", "Buccanee" },
            { "cid_373_athena_commando_m_pirate01", "Sea Wolf" },
            { "cid_376_athena_commando_m_darkshama", "Shaman" },
            { "cid_377_athena_commando_f_darkshaman", "Nightwitch" },
            { "cid_378_athena_commando_m_furnaceface", "Ruin" },
            { "cid_379_athena_commando_m_battlehoundfire", "Molten Battle Hound" },
            { "cid_380_athena_commando_f_darkviking_fire", "Molten Valkyrie" },
            { "cid_386_athena_commando_m_streetopsstealth", "Stealth Reflex" },
            { "cid_388_athena_commando_m_thebomb", "Splode" },
            { "cid_389_athena_commando_f_spacebunny", "Gemini" },
            { "cid_393_athena_commando_m_shiny", "Sterling" },
            { "cid_394_athena_commando_m_moonlightassassin", "Luminos" },
            { "cid_395_athena_commando_f_shatterfly", "Dream" },
            { "cid_396_athena_commando_f_swashbuckler", "Daring Duelist" },
            { "cid_397_athena_commando_f_treasurehunterfashion", "Aura" },
            { "cid_398_athena_commando_m_treasurehunterfashion", "Guild" },
            { "cid_399_athena_commando_f_ashtonboardwalk", "Black Widow Outfit" },
            { "cid_400_athena_commando_m_ashtonsaltlake", "Star-Lord Outfit" },
            { "cid_401_athena_commando_m_miner", "Cole" },
            { "cid_403_athena_commando_m_rooster", "Sentinel" },
            { "cid_404_athena_commando_f_bountyhunter", "Vega" },
            { "cid_405_athena_commando_f_masako", "Demi" },
            { "cid_406_athena_commando_m_stormtracker", "Stratus" },
            { "cid_407_athena_commando_m_battlesuit", "Vendetta" },
            { "cid_408_athena_commando_f_strawberrypilot", "Rox" },
            { "cid_409_athena_commando_m_bunkerman", "Bunker Jonesy" },
            { "cid_410_athena_commando_m_cyberscavenger", "Ether" },
            { "cid_411_athena_commando_f_cyberscavenger", "Versa" },
            { "cid_412_athena_commando_f_raptor", "Velocity" },
            { "cid_413_athena_commando_m_streetdemon", "Cryptic" },
            { "cid_414_athena_commando_f_militaryfashion", "Bracer" },
            { "cid_416_athena_commando_m_assassinsuit", "John Wick" },
            { "cid_418_athena_commando_f_geisha", "Takara" },
            { "cid_420_athena_commando_f_whitetiger", "Wilde" },
            { "cid_423_athena_commando_f_painter", "Clutch" },
            { "cid_424_athena_commando_m_vigilante", "Grind" },
            { "cid_426_athena_commando_f_demonhunter", "Callisto" },
            { "cid_427_athena_commando_m_demonhunter", "Asmodeus" },
            { "cid_428_athena_commando_m_urbanscavenger", "Shot Caller" },
            { "cid_429_athena_commando_f_neonlines", "Breakpoint" },
            { "cid_431_athena_commando_f_stormpilot", "Bolt" },
            { "cid_432_athena_commando_m_balloonhead", "Airhead" },
            { "cid_433_athena_commando_f_tacticaldesert", "Desert Dominator" },
            { "cid_434_athena_commando_f_stealthhonor", "Wonder" },
            { "cid_435_athena_commando_m_munitionsexpertgreenplastic", "Plastic Patroller" },
            { "cid_436_athena_commando_m_reconspecialist", "Relay" },
            { "cid_440_athena_commando_f_bullseyegreenplastic", "Toy Trooper" },
            { "cid_441_athena_commando_f_cyberscavengerblue", "Neo Versa" }
        };

        public static Hashtable Backblings = new Hashtable
        {
            { "bid_001_bluesquire", "Squire Shield" },
            { "bid_002_royaleknight", "Royale Shield" },
            { "bid_003_redknight", "Red Shield" },
            { "bid_004_blackknight", "Black Shield" },
            { "bid_005_raptor", "Raptor Satchel" },
            { "bid_006_skidude", "Alpine Accessories" },
            { "bid_007_skidude_usa", "Alpine Accessories (USA)" },
            { "bid_008_skidude_can", "Alpine Accessories (CAN)" },
            { "bid_009_skidude_gbr", "Alpine Accessories (GBR)" },
            { "bid_010_skidude_fra", "Alpine Accessories (FRA)" },
            { "bid_011_skidude_ger", "Alpine Accessories (GER)" },
            { "bid_012_skidude_chn", "Alpine Accessories (CHN)" },
            { "bid_013_skidude_kor", "Alpine Accessories (KOR)" },
            { "bid_014_skigirl", "Mogul Ski Bag" },
            { "bid_015_skigirl_usa", "Mogul Ski Bag (USA)" },
            { "bid_016_skigirl_can", "Mogul Ski Bag (CAN)" },
            { "bid_017_skigirl_gbr", "Mogul Ski Bag (GBR)" },
            { "bid_018_skigirl_fra", "Mogul Ski Bag (FRA)" },
            { "bid_019_skigirl_ger", "Mogul Ski Bag (GER)" },
            { "bid_021_skigirl_kor", "Mogul Ski Bag (KOR)" },
            { "bid_022_cupid", "Love Wings" },
            { "bid_023_pinkbear", "Cuddle Bow" },
            { "bid_024_space", "Astro" },
            { "bid_025_tactical", "Precision" },
            { "bid_026_brite", "Brite Bag" },
            { "bid_027_scavenger", "Rust Bucket" },
            { "bid_028_spaceblack", "Dark Matter" },
            { "bid_029_retrogrey", "Backup Plan" },
            { "bid_030_tacticalrogue", "Catalyst" },
            { "bid_031_dinosaur", "Scaly" },
            { "bid_032_foundermale", "Pursuit" },
            { "bid_033_founderfemale", "Skirmish" },
            { "bid_034_rockerpunk", "Six String" },
            { "bid_035_scathach", "Buckler" },
            { "bid_036_raven", "Iron Cage" },
            { "bid_037_bunnymale", "Hard Boiled" },
            { "bid_038_bunnyfemale", "Eggshell" },
            { "bid_039_spaceblackfemale", "Dark Void" },
            { "bid_040_wukong", "Royale Flags" },
            { "bid_041_pajamaparty", "Hatchling" },
            { "bid_042_fishhead", "Fish Tank" },
            { "bid_043_pizza", "Special Delivery" },
            { "bid_044_robo", "Steelcast" },
            { "bid_045_tacticaljungle", "Standard Issue" },
            { "bid_047_candy", "Goodie Bag" },
            { "bid_048_graffiti", "Tag Bag" },
            { "bid_049_tacticalwoodland", "True North" },
            { "bid_050_hazmat", "Pathogen" },
            { "bid_051_merman", "Mertank" },
            { "bid_052_hazmatfemale", "Contagion" },
            { "bid_053_jailbirdmale", "Strongbox" },
            { "bid_054_jailbirdfemale", "Burgle Bag" },
            { "bid_055_psburnout", "Blue Shift" },
            { "bid_056_fighterpilot", "Bogey Bag" },
            { "bid_057_visitor", "Offworld Rig" },
            { "bid_058_darkeagle", "Battle Shroud" },
            { "bid_059_wwiipilot", "Last Gasp" },
            { "bid_060_darkninja", "Ominous Orb" },
            { "bid_061_carbideorange", "Stabilizer" },
            { "bid_062_gumshoe", "Evidence Bag" },
            { "bid_063_cuchulainn", "Crested Cape" },
            { "bid_064_fuzzybearind", "Blasting Cap" },
            { "bid_065_carbideblack", "Destabilizer" },
            { "bid_066_speedyred", "Deflector" },
            { "bid_067_gumshoefemale", "Confidential Case" },
            { "bid_068_gumshoedark", "Cluefinder" },
            { "bid_069_decomale", "Venturion Cape" },
            { "bid_070_decofemale", "Ventura Cape" },
            { "bid_071_vikingfemale", "Rearguard" },
            { "bid_072_vikingmale", "Enduring Cape" },
            { "bid_073_darkviking", "Frozen Shroud" },
            { "bid_074_lifeguardfemale", "Pool Party" },
            { "bid_075_tacticalbadass", "Uplink" },
            { "bid_076_shark", "Shark Fin" },
            { "bid_077_wegame", "Insignia" },
            { "bid_078_streetracercobrafemale", "Ballistic" },
            { "bid_079_penguin", "Penguin" },
            { "bid_080_streetracercobramale", "Bat Attitude" },
            { "bid_081_scubamale", "Diving Tank" },
            { "bid_082_scubafemale", "Air Tank" },
            { "bid_083_lifeguardmale", "Rescue Ring" },
            { "bid_084_birthday2018", "Birthday Cake" },
            { "bid_085_modernmilitary", "Paradigm" },
            { "bid_086_exercisefemale", "Back Plate" },
            { "bid_087_exercisemale", "Boombox" },
            { "bid_088_sushichefmale", "Chef's Choice" },
            { "bid_089_streetracerwhitefemale", "Ignition" },
            { "bid_090_streetracerwhitemale", "Lane Splitter" },
            { "bid_091_durrrburgerhero", "Deep Fried" },
            { "bid_092_fuzzybearpanda", "Bamboo" },
            { "bid_093_hippiemale", "Summer Strummer" },
            { "bid_094_hippiefemale", "Hip Shakers" },
            { "bid_095_ravenquillfemale", "Dark Wings" },
            { "bid_096_bikermale", "Road Ready" },
            { "bid_097_bikerfemale", "Road Flair" },
            { "bid_098_bluesamuraimale", "Sashimono" },
            { "bid_099_bluesamuraifemale", "Shiro" },
            { "bid_100_darkpaintballer", "Subjugator" },
            { "bid_101_blingfemale", "Swag Bag" },
            { "bid_102_buckles", "Slashed" },
            { "bid_103_clawed", "Buckled" },
            { "bid_104_yellowzip", "Vintage" },
            { "bid_105_ghostportal", "Ghost Portal" },
            { "bid_106_garagebandmale", "Kick Drum" },
            { "bid_107_garagebandfemale", "Keytar" },
            { "bid_108_blingmale", "Cuff Case" },
            { "bid_108_hacivatmale", "Crafted Carrier" },
            { "bid_109_medicmale", "Care Package" },
            { "bid_110_medicfemale", "Gurney Gear" },
            { "bid_111_clownfemale", "Battle Balloon" },
            { "bid_112_clownmale", "Balloon Llama" },
            { "bid_113_darkvikingfemale", "Valkyrie Wings" },
            { "bid_114_modernmilitaryred", "Telemetry" },
            { "bid_116_dieselpunkfemale", "Airflow" },
            { "bid_117_octoberfestmale", "Clockworks" },
            { "bid_118_octoberfestfemale", "Pretzel Protector" },
            { "bid_119_vampirefemale", "Dusk Wings" },
            { "bid_120_werewolf", "Wolfpack" },
            { "bid_121_redriding", "Fabled Cape" },
            { "bid_122_calloweentomato", "Night Cloak" },
            { "bid_123_fortnitedj", "Waveform" },
            { "bid_126_darkbomber", "Dark Bag" },
            { "bid_127_plaguemale", "Dismal Cape" },
            { "bid_128_plaguefemale", "Arcanum" },
            { "bid_129_pumpkinslice", "Mouldering Cloak" },
            { "bid_130_vampiremale02", "Coven Cape" },
            { "bid_131_blackwidowfemale", "Long Legs" },
            { "bid_132_blackwidowmale", "Spider Shield" },
            { "bid_133_guanyu", "Loyal Shield" },
            { "bid_134_militaryfashion", "Top Notch" },
            { "bid_135_muertosfemale", "Calavera" },
            { "bid_136_muertosmale", "Spirit Cape" },
            { "bid_137_evilcowboy", "Shackled Stone" },
            { "bid_138_celestial", "Galactic Disc" },
            { "bid_139_fuzzybearcalloween", "Goodie Gourd" },
            { "bid_140_streetopsmale", "Response Unit" },
            { "bid_141_streetopsfemale", "Reaction Tank" },
            { "bid_142_samuraiultra", "Bladed Wings" },
            { "bid_143_madcommandermale", "Spike Chamber" },
            { "bid_144_madcommanderfemale", "Puncture Pack" },
            { "bid_145_animaljacketsmale", "Woofs" },
            { "bid_146_animaljacketsfemale", "Nibbles" },
            { "bid_147_lilkev", "Lil' Kev" },
            { "bid_148_robotred", "E.L.I.M." },
            { "bid_149_wizard", "Spellbinder" },
            { "bid_150_witch", "Tome Pouch" },
            { "bid_151_sushicheffemale", "Shrimpy" },
            { "bid_152_cornedmaskmale", "Trusty Tusks" },
            { "bid_153_cornedmaskfemale", "White Fang" },
            { "bid_154_feathers", "Hatchback" },
            { "bid_155_snipercoodmale", "Scope Satchel" },
            { "bid_156_snipercoodfemale", "Sight Sling" },
            { "bid_157_mothmale", "Wingback" },
            { "bid_158_arcticsnipermale", "Altitude" },
            { "bid_160_tacticalsantamale", "Perfect Present" },
            { "bid_161_snowboardfemale", "Trail Tote" },
            { "bid_162_yetimale", "Ice Cube" },
            { "bid_163_iceking", "Ice Mantle" },
            { "bid_164_snowmanmale", "Slushy Jr." },
            { "bid_165_bluebadassfemale", "Signal Hub" },
            { "bid_166_ravenwintermale", "Frozen Iron Cage" },
            { "bid_167_redknightwinterfemale", "Frozen Red Shield" },
            { "bid_168_cupidwintermale", "Frozen Love Wings" },
            { "bid_169_mathmale", "Tabulator" },
            { "bid_170_mathfemale", "Techie" },
            { "bid_178_angel", "Ark" },
            { "bid_181_snowninjamale", "Snowfoot" },
            { "bid_182_nutcrackermale", "Birdshot" },
            { "bid_186_gingerbreadmale", "Mini Marauder" },
            { "bid_187_gingerbreadfemale", "Giddy Gunner" },
            { "bid_189_streetgothmale", "Eternal" },
            { "bid_190_streetgothfemale", "Stitches" },
            { "bid_191_winterghoulmale", "Shadow Wings" },
            { "bid_192_wintercolidayfemale", "Combat Wreath" },
            { "bid_200_snowninjafemale", "Snowbrand" },
            { "bid_208_cupiddarkmale", "Fallen Wings" },
            { "bid_209_robottroublemale", "Board Bag" },
            { "bid_210_robottroublefemale", "Cannister Carrier" },
            { "bid_211_skullbrite", "Skully Satchel" },
            { "bid_213_icecream", "Sno Cone" },
            { "bid_176_nautilusmale", "Rebreather" },
            { "bid_177_nautilusfemale", "Octotank" },
            { "bid_214_lovellama", "Sweetheart" },
            { "bid_215_masterkey", "Master Portal" },
            { "bid_216_pirateprogressive", "Mutiny" },
            { "bid_217_shinyfemale", "High Caliber" },
            { "bid_218_medusa", "Cobra" },
            { "bid_219_farmermale", "Haystacks" },
            { "bid_220_farmerfemale", "Sun Sprout" },
            { "bid_221_aztecmale", "Hypnotic" },
            { "bid_222_aztecfemale", "Sun Wings" },
            { "bid_223_orangecamo", "Oscilloscope" },
            { "bid_224_techopsblue", "Carbon Pack" },
            { "bid_201_wavymanmale", "Bendie Inflator" },
            { "bid_202_wavymanfemale", "Twistie Inflator" },
            { "bid_225_bandageninjamale", "Katana Kunai" },
            { "bid_226_bandageninjafemale", "Dual Kama" },
            { "bid_227_sciopsfemale", "Omission" },
            { "bid_228_sciopsmale", "Commission" },
            { "bid_230_tropicalmale", "Banana Bag" },
            { "bid_231_tropicalfemale", "Pineapple Strummer" },
            { "bid_235_ceist", "Crystal Llama" },
            { "bid_242_furnaceface", "Dying Light" },
            { "bid_248_pilots", "Gauge" },
            { "bid_249_streetopsstealth", "Stealth Response Unit" },
            { "bid_251_spacebunny", "Cryo Hops" },
            { "bid_250_thebomb", "Volatile" },
            { "bid_252_evilbunny", "Floppy" },
            { "bid_253_coppityheist", "Bunny Bag" },
            { "bid_254_shinymale", "Diamond Star" },
            { "bid_255_moonlightassassin", "Lunar Light" },
            { "bid_256_shatterfly", "Shattered Wing" },
            { "bid_257_swashbuckler", "Slice & dice" },
            { "bid_258_ashtonboardwalk", "Widows Pack" },
            { "bid_259_ashton_saltlake", "Star-Lord Pack" },
            { "bid_261_rooster", "Hot Wing" },
            { "bid_262_bountycunterfemale", "Go bag" },
            { "bid_263_masako", "Scarlet Edge" },
            { "bid_264_stormtracker", "Backtracker" },
            { "bid_265_battlesuit", "Retribution" },
            { "bid_266_bunkerman", "Nana Cape" },
            { "bid_267_cyberscavengermale", "CnXn" },
            { "bid_268_cyberscavengerfemale", "Phrenzy" },
            { "bid_269_raptorfemale", "Bomber bag" },
            { "bid_270_streetdemon", "Spectral Spine" },
            { "bid_271_assassinsuitmale", "Assassin Pack" },
            { "bid_273_assassinsuitcoin", "Gold Token" },
            { "bid_275_geisha", "Gaze" },
            { "bid_277_whitetiger", "Palette Pack" },
            { "bid_278_vigilanteboard", "Back Board" }

        };

        public static Hashtable Pickaxes = new Hashtable
        {
            { "boltonpickaxe", "Close Shave" },
            { "defaultpickaxe", "Pickaxe" },
            { "halloweenscythe", "Reaper" },
            { "happypickaxe", "Lucky" },
            { "pickaxe_lockjaw", "Raider's Revenge" },
            { "sicklebatpickaxe", "Batsickle" },
            { "skiicepickaxe", "Cliffhanger" },
            { "spikypickaxe", "Spiky" },
            { "pickaxe_deathvalley", "Death Valley" },
            { "pickaxe_flamingo", "Pink Flamingo" },
            { "pickaxe_id_011_medieval", "Axecalibur" },
            { "pickaxe_id_012_district", "Pulse Axe" },
            { "pickaxe_id_013_teslacoil", "AC/DC" },
            { "pickaxe_id_014_wintercamo", "Ice Breaker" },
            { "pickaxe_id_015_holidaycandycane", "Candy Axe" },
            { "pickaxe_id_016_disco", "Disco Brawl" },
            { "pickaxe_id_017_shark", "Chomp Jr." },
            { "pickaxe_id_018_anchor", "Bottom Feeder" },
            { "pickaxe_id_019_heart", "Tat Axe" },
            { "pickaxe_id_020_keg", "Party Animal" },
            { "pickaxe_id_021_megalodon", "Tooth Pick" },
            { "pickaxe_id_022_holidaygiftwrap", "You Shouldn't Have!" },
            { "pickaxe_id_023_skiboot", "Ski Boot" },
            { "pickaxe_id_024_plunger", "Plunja" },
            { "pickaxe_id_025_dragon", "Dragon Axe" },
            { "pickaxe_id_026_brite", "Rainbow Smash" },
            { "pickaxe_id_027_scavenger", "Sawtooth" },
            { "pickaxe_id_028_space", "EVA" },
            { "pickaxe_id_029_assassin", "Trusty No. 2" },
            { "pickaxe_id_030_artdeco", "Empire Axe" },
            { "pickaxe_id_031_squeak", "Pick Squeak" },
            { "pickaxe_id_032_tactical", "Tactical Spade" },
            { "pickaxe_id_033_potofgold", "Pot O' Gold" },
            { "pickaxe_id_034_rockerpunk", "Anarchy Axe" },
            { "pickaxe_id_035_prismatic", "Spectral Axe" },
            { "pickaxe_id_036_cuchulainn", "Silver Fang" },
            { "pickaxe_id_037_stealth", "Spectre" },
            { "pickaxe_id_038_carrot", "Carrot Stick" },
            { "pickaxe_id_039_tacticalblack", "Instigator" },
            { "pickaxe_id_040_pizza", "Axeroni" },
            { "pickaxe_id_041_pajamaparty", "Bitemark" },
            { "pickaxe_id_042_circuitbreaker", "Cutting Edge" },
            { "pickaxe_id_043_orbitingplanets", "Global Axe" },
            { "pickaxe_id_044_tacticalurbanhammer", "Tenderizer" },
            { "pickaxe_id_045_valor", "Gale Force" },
            { "pickaxe_id_046_candy", "Lollipopper" },
            { "pickaxe_id_047_carbideblue", "Positron" },
            { "pickaxe_id_048_carbideblack", "Onslaught" },
            { "pickaxe_id_049_metal", "Persuader" },
            { "pickaxe_id_050_graffiti", "Renegade Roller" },
            { "pickaxe_id_051_neonglow", "Glow Stick" },
            { "pickaxe_id_052_hazmat", "Autocleave" },
            { "pickaxe_id_053_deco", "Airfoil" },
            { "pickaxe_id_054_filmcamera", "Director's Cut" },
            { "pickaxe_id_055_stop", "Stop Axe" },
            { "pickaxe_id_056_venus", "Tendril" },
            { "pickaxe_id_057_jailbird", "Nite Owl" },
            { "pickaxe_id_058_basketball", "Slam Dunk" },
            { "pickaxe_id_059_darkeagle", "Oracle Axe" },
            { "pickaxe_id_060_darkninja", "Fated Frame" },
            { "pickaxe_id_061_wwiipilot", "Propeller Axe" },
            { "pickaxe_id_062_soccer", "Elite Cleat" },
            { "pickaxe_id_063_vuvuzela", "Vuvuzela" },
            { "pickaxe_id_064_gumshoe", "Magnifying Axe" },
            { "pickaxe_id_065_speedyred", "Razor Edge" },
            { "pickaxe_id_066_flintlockred", "Crimson Axe" },
            { "pickaxe_id_067_taxi", "Victory Lap" },
            { "pickaxe_id_068_drift", "Rift Edge" },
            { "pickaxe_id_069_darkviking", "Permafrost" },
            { "pickaxe_id_070_viking", "Forebearer" },
            { "pickaxe_id_071_streetracer", "Lug Axe" },
            { "pickaxe_id_072_luchador", "Piledriver" },
            { "pickaxe_id_073_balloon", "Balloon Axe" },
            { "pickaxe_id_074_sharpdresser", "Studded Axe" },
            { "pickaxe_id_075_huya", "Pointer" },
            { "pickaxe_id_076_douyu", "Power Grip" },
            { "pickaxe_id_077_carbidewhite", "Resonator" },
            { "pickaxe_id_078_lifeguard", "Rescue Paddle" },
            { "pickaxe_id_079_modernmilitary", "Caliper" },
            { "pickaxe_id_080_scuba", "Harpoon Axe" },
            { "pickaxe_id_081_streetracercobra", "Clutch Axe" },
            { "pickaxe_id_082_sushichef", "Filet Axe" },
            { "pickaxe_id_083_exercise", "Axercise" },
            { "pickaxe_id_084_durrburgerhero", "Patty Whacker" },
            { "pickaxe_id_085_wukong", "Jingu Bang" },
            { "pickaxe_id_086_biker", "Throttle" },
            { "pickaxe_id_087_hippie", "Drumbeat" },
            { "pickaxe_id_088_psburnout", "Controller" },
            { "pickaxe_id_089_ravenquill", "Iron Beak" },
            { "pickaxe_id_090_samuraiblue", "Cat's Claw" },
            { "pickaxe_id_091_hacivat", "Tree Splitter" },
            { "pickaxe_id_092_bling", "Crowbar" },
            { "pickaxe_id_093_medic", "Flatliner" },
            { "pickaxe_id_094_football", "Upright Axe" },
            { "pickaxe_id_095_footballtrophy", "Golden Pigskin" },
            { "pickaxe_id_096_footballreferee", "First Downer" },
            { "pickaxe_id_097_raptorarcticcamo", "Chill-Axe" },
            { "pickaxe_id_098_garageband", "Lead Swinger" },
            { "pickaxe_id_099_modernmilitaryred", "Pinpoint" },
            { "pickaxe_id_100_dieselpunk", "Turbine" },
            { "pickaxe_id_101_octoberfest", "Axcordion" },
            { "pickaxe_id_102_redriding", "Guiding Glow" },
            { "pickaxe_id_103_fortnitedj", "Smash Up" },
            { "pickaxe_id_104_cowgirl", "Reckoning" },
            { "pickaxe_id_106_darkbomber", "Thunder Crash" },
            { "pickaxe_id_107_calloweentomato", "Night Slicer" },
            { "pickaxe_id_107_plague", "Herald's Wand" },
            { "pickaxe_id_108_pumpkinslice", "Carver" },
            { "pickaxe_id_109_skulltrooper", "Skull Sickle" },
            { "pickaxe_id_110_vampire", "Moonrise" },
            { "pickaxe_id_111_blackwidow", "Web Breaker" },
            { "pickaxe_id_112_guanyu", "Guandao" },
            { "pickaxe_id_113_muertos", "Six String Striker" },
            { "pickaxe_id_114_badasscowboycowskull", "Longhorn" },
            { "pickaxe_id_115_evilcowboy", "Dark Shard" },
            { "pickaxe_id_116_celestial", "Stellar Axe" },
            { "pickaxe_id_121_robotred", "A.X.E." },
            { "pickaxe_id_122_witch", "Spellslinger" },
            { "pickaxe_id_123_cornedmask", "Gatekeeper" },
            { "pickaxe_id_124_feathers", "Scrambler" },
            { "pickaxe_id_125_moth", "Lamp" },
            { "pickaxe_id_126_yeti", "Abominable Axe" },
            { "pickaxe_id_127_rhino", "Uni-horn" },
            { "pickaxe_id_131_nautilus", "TBD" },
            { "pickaxe_id_131_neoncat", "Scratchmark" },
            { "pickaxe_id_132_arcticsniper", "Scorcher" },
            { "pickaxe_id_133_iceking", "Ice Scepter" },
            { "pickaxe_id_134_snowman", "Icicle" },
            { "pickaxe_id_135_snowninja", "Inverted Blade" },
            { "pickaxe_id_136_math", "T-Square" },
            { "pickaxe_id_137_nutcracker", "Snow Globe" },
            { "pickaxe_id_138_gnome", "Cold Snap" },
            { "pickaxe_id_139_gingerbread", "Cookie Cutter" },
            { "pickaxe_id_140_streetgoth", "Vision" },
            { "pickaxe_id_141_krampus", "Brat Catcher" },
            { "pickaxe_id_142_teriyakifish", "Bootstraps" },
            { "pickaxe_id_143_flintlockwinter", "Frozen Axe" },
            { "pickaxe_id_144_angel", "Virtue" },
            { "pickaxe_id_145_icemaiden", "Flurry" },
            { "pickaxe_id_146_militaryfashion", "Clean Cut" },
            { "pickaxe_id_158_fuzzybear", "Cuddle Paw" },
            { "pickaxe_id_159_robottrouble", "Crossroads" },
            { "pickaxe_id_160_icecream", "Ice Pop" },
            { "pickaxe_id_163_pirateoctopus", "Swag Smasher" },
            { "pickaxe_id_164_dragonninja", "Dragon's Claw" },
            { "pickaxe_id_165_masterkey", "Lockpick" },
            { "pickaxe_id_166_shiny", "Flawless" },
            { "pickaxe_id_167_medusa", "Snakebite" },
            { "pickaxe_id_168_bandolier", "Machete" },
            { "pickaxe_id_169_farmer", "Gold Digger" },
            { "pickaxe_id_170_aztec", "Axetec" },
            { "pickaxe_id_171_orangecamo", "Brute Force" },
            { "pickaxe_id_172_bandageninja", "Quickstrike" },
            { "pickaxe_id_173_sciops", "Psionic Edge" },
            { "pickaxe_id_175_tropical", "Fresh Cut" },
            { "pickaxe_id_179_starwand", "Star Wand" },
            { "pickaxe_id_180_tristar", "Tri-Star" },
            { "pickaxe_id_181_log", "Stumpy" },
            { "pickaxe_id_177_evilsuit", "Crimson Scythe" },
            { "pickaxe_id_187_furnaceface", "Dread" },
            { "pickaxe_id_189_streetopsstealth", "Stealth Angular Axe" },
            { "pickaxe_id_194_thebomb", "Shrapnel" },
            { "pickaxe_id_195_spacebunny", "Plasma Carrot" },
            { "pickaxe_id_199_shinycammer", "Silver Sledge" },
            { "pickaxe_id_200_moonlightassassin", "Astral Axe" },
            { "pickaxe_id_201_swashbuckler", "Flint Striker" },
            { "pickaxe_id_202_ashtonboardwalk", "Widow's Bite" },
            { "pickaxe_id_203_ashtonsaltlake", "Guardian Axe" },
            { "pickaxe_id_204_miner", "Rockbreaker" },
            { "pickaxe_id_205_strawberrypilot", "Vox" },
            { "pickaxe_id_206_strawberrypilot_1c", "Harmonic Axes" },
            { "pickaxe_id_207_bountycunter", "Revoker" },
            { "pickaxe_id_208_masako", "Scarlet Scythe" },
            { "pickaxe_id_209_battlesuit", "Mech Axe" },
            { "pickaxe_id_210_bunkerman", "Bunker Basher" },
            { "pickaxe_id_211_bunkerman_1c", "Ripe Rippers" },
            { "pickaxe_id_212_cyberscavenger", "Web Wrecker" },
            { "pickaxe_id_213_assassinsuitsledgehammer", "Simple Sledge" },
            { "pickaxe_id_214_geisha", "Shamisen" }
        };

        public static Hashtable Gliders = new Hashtable
        {
            { "defaultglider", "Glider" },
            { "dev_testasset", "Dev Test Asset" },
            { "duo_umbrella", "Duo Umbrella" },
            { "dynamicstestglider", "Glider" },
            { "founderglider", "Founder's Glider" },
            { "founderumbrella", "Founder's Umbrella" },
            { "glider_bold", "Modern" },
            { "glider_flames", "Hot Rod" },
            { "glider_flowerpower", "Petunia" },
            { "glider_id_tbd_modernmilitaryred", "TBD" },
            { "glider_mig", "Raptor" },
            { "glider_military", "Warthog" },
            { "glider_prismatic", "Prismatic" },
            { "glider_proxytest", "Glider" },
            { "glider_random", "Random Glider" },
            { "glider_roadtrip", "Roadtrip" },
            { "glider_stealth", "Stealth" },
            { "glider_teststaticparts", "Glider" },
            { "glider_venom", "Wasp" },
            { "glider_voyager", "Voyager" },
            { "glider_warthog", "Mako" },
            { "preseasonglider", "Rainbow Glider" },
            { "preseasonglider_elite", "Rainbow Glider Elite" },
            { "solo_umbrella", "The Umbrella" },
            { "squad_umbrella", "Squad Umbrella" },
            { "umbrella_bronze", "The Umbrella" },
            { "umbrella_gold", "The Umbrella" },
            { "umbrella_paperparasol", "Paper Parasol" },
            { "umbrella_platinum", "The Umbrella" },
            { "umbrella_season_04", "Wet Paint" },
            { "umbrella_season_05", "Beach Umbrella" },
            { "umbrella_season_06", "Webrella" },
            { "umbrella_silver", "The Umbrella" },
            { "umbrella_snowflake", "Snowflake" },
            { "glider_id_001", "Aerial Assault One" },
            { "glider_id_002_medieval", "Sir Glider the Brave" },
            { "glider_id_003_district", "Royale X" },
            { "glider_id_004_disco", "Get Down!" },
            { "glider_id_005_holidaysweater", "Cozy Coaster" },
            { "glider_id_006_wintercamo", "Snow Squall" },
            { "glider_id_007_turtleshell", "Half Shell" },
            { "glider_id_008_graffiti", "Zephyr" },
            { "glider_id_009_candycoat", "Gum Drop" },
            { "glider_id_010_storm", "Cloud Strike" },
            { "glider_id_011_jollyroger", "Jolly Roger" },
            { "glider_id_012_teddybear", "Bear Force One" },
            { "glider_id_013_psblue", "Blue Streak" },
            { "glider_id_014_dragon", "Royale Dragon" },
            { "glider_id_015_brite", "Rainbow Rider" },
            { "glider_id_016_tactical", "Carbon" },
            { "glider_id_017_assassin", "High Octane" },
            { "glider_id_018_twitch", "Slipstream" },
            { "glider_id_019_taxi", "Checker" },
            { "glider_id_020_fighter", "Fighter Kite" },
            { "glider_id_021_scavenger", "Rusty Rider" },
            { "glider_id_022_rockerpunk", "Stage Dive" },
            { "glider_id_023_cuchulainn", "Storm Sigil" },
            { "glider_id_024_reaper", "Feathered Flyer" },
            { "glider_id_025_shuttlea", "Orbital Shuttle" },
            { "glider_id_026_shuttleb", "Deep Space Lander" },
            { "glider_id_027_satelite", "Planetary Probe" },
            { "glider_id_028_googly", "Googly" },
            { "glider_id_029_pajamaparty", "Fossil Flyer" },
            { "glider_id_030_circuitbreaker", "Mainframe" },
            { "glider_id_031_metal", "Solid Strider" },
            { "glider_id_032_tacticalwoodland", "Steadfast" },
            { "glider_id_033_valor", "Wings of Valor" },
            { "glider_id_034_carbideblue", "Intrepid" },
            { "glider_id_035_candy", "Sugar Crash" },
            { "glider_id_036_auroraglow", "Glow Rider" },
            { "glider_id_037_hazmat", "Meltdown" },
            { "glider_id_038_deco", "Triumph" },
            { "glider_id_039_venus", "Venus Flyer" },
            { "glider_id_040_jailbird", "Starry Flight" },
            { "glider_id_041_basketball", "Hang Time" },
            { "glider_id_042_soccer", "Goalbound" },
            { "glider_id_043_darkninja", "Split Wing" },
            { "glider_id_044_pterodactyl", "Pterodactyl" },
            { "glider_id_045_carbideblack", "Terminus" },
            { "glider_id_046_gumshoe", "Viceroy Mark I" },
            { "glider_id_047_speedyred", "Forerunner" },
            { "glider_id_048_viking", "Conquest" },
            { "glider_id_049_lifeguard", "Splashdown" },
            { "glider_id_050_streetracercobra", "Cruiser" },
            { "glider_id_051_luchador", "Libre" },
            { "glider_id_052_bedazzled", "Rhinestone Rider" },
            { "glider_id_053_huya", "Rush" },
            { "glider_id_054_douyu", "Helium" },
            { "glider_id_055_streetracerblack", "Downshift" },
            { "glider_id_056_carbidewhite", "Aurora" },
            { "glider_id_057_modernmilitary", "Servo" },
            { "glider_id_058_shark", "Laser Chomp" },
            { "glider_id_059_durrburgerhero", "Flying Saucer" },
            { "glider_id_060_exercise", "Windbreaker" },
            { "glider_id_061_streetracerbiker", "Cyclone" },
            { "glider_id_062_streetracerwhite", "White Squall" },
            { "glider_id_063_sushichef", "Flying Fish" },
            { "glider_id_064_biker", "Blaze" },
            { "glider_id_065_hippie", "Tie-dye Flyer" },
            { "glider_id_066_samuraiblue", "Purrfect." },
            { "glider_id_067_psburnout", "Flappy" },
            { "glider_id_068_garageband", "Hot Ride" },
            { "glider_id_069_hacivat", "Shadow Puppet" },
            { "glider_id_070_darkviking", "Frostwing" },
            { "glider_id_071_football", "Touchdown" },
            { "glider_id_072_bling", "Safecracker" },
            { "glider_id_073_medic", "Airlift" },
            { "glider_id_074_raptorarcticcamo", "Cold Front" },
            { "glider_id_075_modernmilitaryred", "Rotor" },
            { "glider_id_076_dieselpunk", "Dirigible" },
            { "glider_id_077_octoberfest", "Oktoberfeast" },
            { "glider_id_078_vampire", "Swarm" },
            { "glider_id_079_redriding", "Picnic" },
            { "glider_id_080_prairiepusher", "Covered Crusader" },
            { "glider_id_081_cowboygunslinger", "Crossfire" },
            { "glider_id_084_plague", "Lamplight" },
            { "glider_id_085_skulltrooper", "Crypt Cruiser" },
            { "glider_id_086_blackwidow", "Hatchling" },
            { "glider_id_087_guanyu", "Divine Dragon" },
            { "glider_id_088_evilcowboy", "Dark Engine" },
            { "glider_id_089_muertos", "Spirit" },
            { "glider_id_090_celestial", "Discovery" },
            { "glider_id_092_streetops", "Pivot" },
            { "glider_id_093_animaljackets", "Poofy Parasail" },
            { "glider_id_094_samuraiultra", "Kabuto" },
            { "glider_id_095_witch", "Magic Wings" },
            { "glider_id_096_cornedmask", "Flying Carp" },
            { "glider_id_097_feathers", "Flappy Flyer" },
            { "glider_id_098_sup", "Hyper" },
            { "glider_id_099_moth", "Flutterbug" },
            { "glider_id_100_yeti", "Rickety Runner" },
            { "glider_id_101_tacticalsanta", "Tactical Sleigh" },
            { "glider_id_103_nautilus", "TBD" },
            { "glider_id_104_durrburger", "Glidurrr" },
            { "glider_id_104_math", "Paper Plane" },
            { "glider_id_105_gingerbread", "Gingersled" },
            { "glider_id_105_snowboard", "Royale Air" },
            { "glider_id_106_fortnitedj", "Equalizer" },
            { "umbrella_season_07", "Snowfall" },
            { "glider_id_120_icecream", "Ice Cream Cruiser" },
            { "glider_id_121_britebomberdeluxe", "Brite Blimp" },
            { "glider_id_123_masterkey", "Lockstep" },
            { "glider_id_124_medusa", "Sky Serpents" },
            { "glider_id_125_bandolier", "Choppa" },
            { "glider_id_127_aztec", "Sunrise" },
            { "glider_id_128_bootybuoy", "Booty Buoy" },
            { "glider_id_129_fireelf", "Cinder" },
            { "umbrella_season_08", "Palm Leaf" },
            { "glider_id_130_sciops", "Disruptor" },
            { "glider_id_137_streetopsstealth", "Stealth Pivot" },
            { "glider_id_140_shatterfly", "Arcana" },
            { "glider_id_141_ashtonboardwalk", "Avengers Quinjet" },
            { "glider_id_142_ashtonsaltlake", "The Milano" },
            { "glider_id_143_battlesuit", "Retaliator" },
            { "glider_id_144_strawberrypilot", "Turbo Spin" },
            { "glider_id_145_stormtracker", "Tailwind Twister" },
            { "glider_id_146_masako", "Scarlet Strike" },
            { "glider_id_147_raptor", "Assault Bomber" },
            { "glider_id_148_cyberscavenger", "Tech Turbine" },
            { "umbrella_season_09", "Holographic" },
            { "glider_id_149_geisha", "Engage" },
            { "umbrella_assassinsuit", "One Shot" }
        };
    }
}
